# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20170124_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpagepost',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blogpagepost',
            name='post_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpagepost',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpagepost',
            name='text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
